declare module 'myanimelist-oauth';
// declare module "myanimelist-oauth" {
//   interface MyAnimeListOAuth {
//     callback: string,
//     clientID: string,
//     clientSecret?: string,
//     codeChallange?: string,
//     state?: string
//   }

//   return myanimelist_oauth
// }

// export {}

/** generated by dts-gen */

// export = myanimelist_oauth;

// declare function myanimelist_oauth(...args: any[]): any;
